# Generated by Django 4.2.5 on 2023-09-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="stu_uid",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
